-- RadiantWay Travel — demo content, generated from server/prisma/seed-data.js.
--
-- Import AFTER radiantway_mysql_schema.sql, into the same database. Every table
-- must be empty: these are plain INSERTs, so running it twice duplicates rows
-- (and fails on Package.slug, which is unique).
--
-- The admin account is deliberately absent — its password has to be hashed, so
-- it comes from `npm run seed` or an INSERT you build yourself.
--
-- Regenerate: node server/prisma/gen-seed-sql.mjs > server/prisma/seed-data.sql

SET NAMES utf8mb4;

INSERT INTO `Package` (`slug`, `name`, `category`, `country`, `region`, `city`, `tagline`, `nights`, `days`, `occupancy`, `price`, `currency`, `hotelStars`, `rating`, `featured`, `published`, `order`, `image`, `gallery`, `tags`, `includes`, `highlights`, `itinerary`, `createdAt`, `updatedAt`) VALUES
  ('escape-to-armenia', 'Escape to Armenia', 'tour', 'Armenia', 'Caucasus', 'Yerevan', 'Ancient monasteries, alpine lakes & warm hospitality', 3, 4, 'Quad sharing', 1250, 'AED', 4, 4.9, 1, 1, 0, 'https://images.unsplash.com/photo-1585687501004-615dfdfb6f37?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1585687501004-615dfdfb6f37?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1600241318523-1a2a56b8a41f?auto=format&fit=crop&w=1200&q=80"]', '["Culture","Nature","Best Seller"]', '["Return flights from UAE","4★ hotel stay","Daily breakfast","Airport transfers","Yerevan city tour"]', '["Explore Yerevan","Lake Sevan — the Pearl of Armenia","Garni Temple & Geghard","Cascade Complex"]', '[{"day":1,"title":"Arrival in Yerevan","detail":"Warm welcome at Zvartnots Airport, private transfer to your 4★ hotel and an evening stroll along Republic Square."},{"day":2,"title":"Yerevan City & Cascade","detail":"Discover the pink-stone capital — the Cascade Complex, Opera House, museums and vibrant cafés."},{"day":3,"title":"Lake Sevan & Highlands","detail":"Day trip to the sparkling Lake Sevan, Sevanavank monastery and the alpine countryside."},{"day":4,"title":"Departure","detail":"Leisurely breakfast, last-minute souvenir shopping and transfer back to the airport."}]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('discover-istanbul', 'Discover Istanbul', 'tour', 'Türkiye', 'Europe & Asia', 'Istanbul', 'Where two continents and a thousand years meet', 4, 5, 'Twin sharing', 1690, 'AED', 4, 4.8, 1, 1, 1, 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=1200&q=80"]', '["Culture","City Break","Popular"]', '["Return flights from UAE","4★ hotel stay","Daily breakfast","Airport transfers","Bosphorus cruise"]', '["Blue Mosque & Hagia Sophia","Grand Bazaar","Bosphorus dinner cruise","Topkapi Palace"]', '[{"day":1,"title":"Arrival in Istanbul","detail":"Private transfer to your hotel in the heart of the old city, evening at leisure."},{"day":2,"title":"Old City Wonders","detail":"Hagia Sophia, the Blue Mosque, Topkapi Palace and the Hippodrome."},{"day":3,"title":"Bazaars & Bosphorus","detail":"The Grand Bazaar, Spice Market and an unforgettable Bosphorus dinner cruise."},{"day":4,"title":"Asian Side & Free Time","detail":"Cross to the Asian shore, explore Kadıköy, then shop or relax at your own pace."},{"day":5,"title":"Departure","detail":"Breakfast and airport transfer with memories to last a lifetime."}]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('russian-adventure', 'Russian Adventure', 'tour', 'Russia', 'Europe', 'Moscow', 'Imperial grandeur, golden domes & endless boulevards', 4, 5, 'Twin sharing', 2350, 'AED', 4, 4.9, 1, 1, 2, 'https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1547448415-e9f5b28e570d?auto=format&fit=crop&w=1200&q=80"]', '["Culture","City Break"]', '["Return flights from UAE","4★ hotel stay","Daily breakfast","Airport transfers","Kremlin & Red Square tour"]', '["Red Square & St Basil’s","The Kremlin","Moscow Metro tour","Bolshoi district"]', '[{"day":1,"title":"Arrival in Moscow","detail":"Meet & greet, transfer to your central hotel, evening walk to illuminated Red Square."},{"day":2,"title":"Kremlin & Red Square","detail":"Guided tour of the Kremlin, Cathedral Square and iconic St Basil’s Cathedral."},{"day":3,"title":"Metro & Museums","detail":"The palatial Moscow Metro, Tretyakov Gallery and Arbat Street."},{"day":4,"title":"Day at Leisure","detail":"Optional day trip or free time for shopping and cafés."},{"day":5,"title":"Departure","detail":"Breakfast and transfer to the airport."}]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('maldives-getaway', 'Maldives Getaway', 'tour', 'Maldives', 'Indian Ocean', 'Malé', 'Turquoise lagoons and your own slice of paradise', 4, 5, 'Twin sharing', 4200, 'AED', 5, 5, 1, 1, 3, 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=80"]', '["Beach","Honeymoon","Luxury"]', '["Return flights from UAE","5★ resort stay","Half board","Speedboat transfers","Sunset cruise"]', '["Overwater villa","Snorkelling & reefs","Sunset dolphin cruise","Spa & wellness"]', '[{"day":1,"title":"Arrival in Malé","detail":"Speedboat transfer to your resort, welcome drinks and villa check-in."},{"day":2,"title":"Reef & Lagoon","detail":"Snorkelling over vibrant coral reefs and a lazy afternoon by the lagoon."},{"day":3,"title":"Island Hopping","detail":"Visit a local island and enjoy a sunset dolphin cruise."},{"day":4,"title":"Spa & Relax","detail":"Wellness day — spa treatments, watersports and beachfront dining."},{"day":5,"title":"Departure","detail":"Final breakfast and speedboat transfer back to Malé."}]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('georgia-highlights', 'Georgia Highlights', 'tour', 'Georgia', 'Caucasus', 'Tbilisi', 'Cobbled old towns, wine valleys and dramatic peaks', 4, 5, 'Triple sharing', 1550, 'AED', 4, 4.8, 0, 1, 4, 'https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=1200&q=80"]', '["Culture","Nature","Wine"]', '["Return flights from UAE","4★ hotel stay","Daily breakfast","Airport transfers","Kazbegi day trip"]', '["Old Tbilisi","Kazbegi & Gergeti","Wine tasting in Kakheti","Sulphur baths"]', '[{"day":1,"title":"Arrival in Tbilisi","detail":"Transfer to hotel and an evening walk through the atmospheric old town."},{"day":2,"title":"Tbilisi City Tour","detail":"Narikala Fortress, sulphur baths and the charming backstreets."},{"day":3,"title":"Kazbegi Mountains","detail":"Journey along the Military Highway to the breathtaking Gergeti Trinity Church."},{"day":4,"title":"Kakheti Wine Region","detail":"Tastings in Georgia’s legendary wine country."},{"day":5,"title":"Departure","detail":"Breakfast and airport transfer."}]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('baku-azerbaijan', 'Baku Escape', 'tour', 'Azerbaijan', 'Caucasus', 'Baku', 'Flame towers, Caspian breezes and old-world charm', 3, 4, 'Twin sharing', 1450, 'AED', 4, 4.7, 0, 1, 5, 'https://images.unsplash.com/photo-1601921004897-c1e6d1f9a4d4?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1601921004897-c1e6d1f9a4d4?auto=format&fit=crop&w=1200&q=80"]', '["City Break","Culture"]', '["Return flights from UAE","4★ hotel stay","Daily breakfast","Airport transfers","Old City tour"]', '["Flame Towers","Icherisheher Old City","Highland Park views","Caspian promenade"]', '[{"day":1,"title":"Arrival in Baku","detail":"Transfer to hotel and a stroll along the Caspian boulevard."},{"day":2,"title":"Old & New Baku","detail":"Icherisheher old city, Maiden Tower and the futuristic Flame Towers."},{"day":3,"title":"Absheron & Gobustan","detail":"Ancient petroglyphs, mud volcanoes and burning mountain."},{"day":4,"title":"Departure","detail":"Breakfast and airport transfer."}]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('dubai-city-experience', 'Dubai City Experience', 'tour', 'United Arab Emirates', 'Middle East', 'Dubai', 'Sky-high glamour, golden dunes and modern marvels', 3, 4, 'Twin sharing', 1890, 'AED', 5, 4.9, 0, 1, 6, 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80"]', '["City Break","Family","Luxury"]', '["5★ hotel stay","Daily breakfast","Desert safari","Burj Khalifa tickets"]', '["Burj Khalifa At The Top","Desert safari & BBQ","Dhow dinner cruise","Dubai Mall & Fountain"]', '[{"day":1,"title":"Arrival in Dubai","detail":"Transfer to your 5★ hotel and evening at the Dubai Fountain."},{"day":2,"title":"Modern Dubai","detail":"Burj Khalifa At The Top, Dubai Mall and the Marina."},{"day":3,"title":"Desert Safari","detail":"Dune bashing, camel rides and a starlit BBQ dinner with live shows."},{"day":4,"title":"Departure","detail":"Breakfast and airport transfer."}]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('umrah-package', 'Umrah Journey', 'umrah', 'Saudi Arabia', 'Middle East', 'Makkah & Madinah', 'A spiritually enriching journey, faultlessly organised', 7, 8, 'Quad sharing', 3200, 'AED', 4, 5, 0, 1, 7, 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?auto=format&fit=crop&w=1200&q=80"]', '["Spiritual","Umrah"]', '["Return flights from UAE","Umrah visa","4★ hotels near Haram","Ziyarat tours","Inter-city transfers"]', '["Hotels steps from the Haram","Guided Ziyarat in both cities","Group & family options","Complete visa handling"]', '[{"day":1,"title":"Arrival in Madinah","detail":"Transfer to your hotel near Masjid an-Nabawi."},{"day":2,"title":"Madinah Ziyarat","detail":"Guided visits to the holy sites of Madinah."},{"day":3,"title":"Travel to Makkah","detail":"Comfortable transfer and performing of Umrah."},{"day":4,"title":"Worship & Reflection","detail":"Days of worship at Masjid al-Haram at your own pace."},{"day":8,"title":"Departure","detail":"Final prayers and transfer to the airport."}]', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

INSERT INTO `Destination` (`name`, `blurb`, `image`, `priceFrom`, `packageSlug`, `published`, `order`, `createdAt`, `updatedAt`) VALUES
  ('Armenia', 'Ancient monasteries & alpine lakes', 'https://images.unsplash.com/photo-1585687501004-615dfdfb6f37?auto=format&fit=crop&w=1200&q=80', 1250, 'escape-to-armenia', 1, 0, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Türkiye', 'Two continents, endless wonders', 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=1200&q=80', 1690, 'discover-istanbul', 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Maldives', 'Turquoise lagoons & overwater villas', 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80', 4200, 'maldives-getaway', 1, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Dubai', 'Golden dunes & sky-high glamour', 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80', 1890, 'dubai-city-experience', 1, 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Georgia', 'Old towns, wine valleys & peaks', 'https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=1200&q=80', 1550, 'georgia-highlights', 1, 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Russia', 'Imperial grandeur & golden domes', 'https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=1200&q=80', 2350, 'russian-adventure', 1, 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

INSERT INTO `Visa` (`country`, `flag`, `type`, `processing`, `note`, `price`, `about`, `documentsRequired`, `documentsProvided`, `published`, `order`, `createdAt`, `updatedAt`) VALUES
  ('United States', '🇺🇸', 'B1/B2 Tourist & Business', '3–6 weeks', 'Full appointment scheduling & DS-160 support', 'AED 1,200', 'Our USA B1/B2 Visit Visa assistance makes a notoriously complex process simple. We prepare and review your DS-160, help you schedule your consular interview, and coach you on what to expect — so you walk in confident. Whether it''s tourism, family visits or business, our team maximises your chances of approval.', '["Passport Copy (valid 6+ months)","UAE Visa / Residence Copy","Emirates ID Copy","Recent Photo (white background)","Company NOC Letter","3 Months Bank Statement","DS-160 Confirmation Details"]', '["Professional Assistance","Cover Letter","Application Form Filling","Flight & Hotel Reservations","Travel Insurance","DS-160 Form Preparation","Interview Coaching"]', 1, 0, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('United Kingdom', '🇬🇧', 'Standard Visitor', '3–4 weeks', 'Document checklist & application review', 'AED 950', 'The UK Standard Visitor Visa lets you explore Britain for tourism, family visits or business. We build a tailored document checklist, review every file for consistency, and complete your online application end-to-end — helping you present a strong, credible case to UKVI.', '["Passport Copy (valid 6+ months)","UAE Visa / Residence Copy","Emirates ID Copy","Recent Photo (white background)","Company NOC Letter","3 Months Bank Statement","Proof of Accommodation"]', '["Professional Assistance","Cover Letter","Application Form Filling","Flight & Hotel Reservations","Travel Insurance","Online Application Submission","Appointment Booking"]', 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Schengen', '🇪🇺', 'Short-stay (Type C)', '2–3 weeks', 'Covers 27 European countries', 'AED 850', 'One Schengen visa, twenty-seven European countries. Our Type C short-stay assistance covers everything from choosing the correct consulate to preparing your travel itinerary and insurance. We make sure your application is complete and compliant so you can focus on planning the trip of a lifetime.', '["Passport Copy (valid 6+ months)","UAE Visa / Residence Copy","Emirates ID Copy","Recent Photo (white background)","Company NOC Letter","3 Months Bank Statement","Confirmed Travel Itinerary"]', '["Professional Assistance","Cover Letter","Application Form Filling","Flight & Hotel Reservations","Travel Insurance","Consulate Appointment Booking","Itinerary Preparation"]', 1, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Canada', '🇨🇦', 'Visitor Visa (TRV)', '4–8 weeks', 'Biometrics guidance included', 'AED 1,100', 'Canada''s Temporary Resident Visa (TRV) opens the door to breathtaking landscapes and vibrant cities. We guide you through the online IRCC application, prepare a persuasive cover letter, and walk you through the biometrics step — giving your visitor visa the best possible chance.', '["Passport Copy (valid 6+ months)","UAE Visa / Residence Copy","Emirates ID Copy","Recent Photo (white background)","Company NOC Letter","3 Months Bank Statement","Proof of Funds","Purpose of Travel Letter"]', '["Professional Assistance","Cover Letter","Application Form Filling","Flight & Hotel Reservations","Travel Insurance","IRCC Online Submission","Biometrics Guidance"]', 1, 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Australia', '🇦🇺', 'Visitor (Subclass 600)', '2–4 weeks', 'Online lodgement handled for you', 'AED 1,050', 'The Australian Visitor Visa (Subclass 600) is your gateway to reefs, rainforests and iconic cities. We handle the full ImmiAccount lodgement, assemble your supporting documents, and manage any additional requests from the department — a genuinely hands-off experience for you.', '["Passport Copy (valid 6+ months)","UAE Visa / Residence Copy","Emirates ID Copy","Recent Photo (white background)","Company NOC Letter","3 Months Bank Statement","Proof of Funds"]', '["Professional Assistance","Cover Letter","Application Form Filling","Flight & Hotel Reservations","Travel Insurance","ImmiAccount Lodgement","Document Compilation"]', 1, 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('New Zealand', '🇳🇿', 'Visitor Visa', '3–5 weeks', 'End-to-end application support', 'AED 1,000', 'Discover New Zealand''s stunning fjords, mountains and Māori culture with a Visitor Visa. From your very first consultation to final decision, we prepare your application, verify each document, and keep you updated at every stage — end-to-end support with zero guesswork.', '["Passport Copy (valid 6+ months)","UAE Visa / Residence Copy","Emirates ID Copy","Recent Photo (white background)","Company NOC Letter","3 Months Bank Statement","Proof of Onward Travel"]', '["Professional Assistance","Cover Letter","Application Form Filling","Flight & Hotel Reservations","Travel Insurance","Online Application Submission","Status Tracking"]', 1, 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

INSERT INTO `Testimonial` (`name`, `trip`, `rating`, `quote`, `published`, `order`, `createdAt`, `updatedAt`) VALUES
  ('Ali R.', 'Escape to Armenia', 5, 'My Armenia trip was seamless. Hotels, transfers, and sightseeing were perfectly organised. Highly recommend RadiantWay Travel!', 1, 0, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Fatima S.', 'Discover Istanbul', 5, 'Booking the Turkey package was effortless. Everything from flights to hotel transfers was handled professionally. Istanbul sightseeing was amazing!', 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Omar K.', 'Russian Adventure', 5, 'The Russia package exceeded my expectations. Day trips around Moscow were well organised, and the hotel stay was very comfortable. Truly stress-free travel!', 1, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Sara M.', 'Maldives Getaway', 5, 'An absolute dream. From the speedboat transfer to the overwater villa, every detail was taken care of. We just relaxed and enjoyed our honeymoon.', 1, 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Bilal A.', 'Umrah Journey', 5, 'A spiritually beautiful and perfectly organised Umrah. Hotels were minutes from the Haram and the team supported us every single step of the way.', 1, 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

INSERT INTO `Faq` (`question`, `answer`, `published`, `order`, `createdAt`, `updatedAt`) VALUES
  ('Do you arrange the flights?', 'Yes, all our packages include return flights from major UAE airports, ensuring a seamless travel experience from start to finish.', 1, 0, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Are the hotels central/close to attractions?', 'Yes, we carefully select hotels that are centrally located and close to major attractions, offering both comfort and convenience.', 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Do you help with visa applications?', 'Yes, we provide full support for visa applications, including USA, UK, Schengen, Canada, Australia, and New Zealand. Our team guides you through the entire process.', 1, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Can I book for solo travellers or families?', 'Yes, our packages are flexible and can be tailored for solo travelers, families, or groups, ensuring everyone enjoys a smooth and memorable journey.', 1, 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Do you offer installment payment options?', 'Yes, we offer easy installment plans. You can secure your booking with a small deposit and pay the remaining amount through flexible installments before departure.', 1, 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

INSERT INTO `Service` (`icon`, `title`, `description`, `group`, `published`, `order`, `createdAt`, `updatedAt`) VALUES
  ('Map', 'Tour Packages', 'Curated multi-day itineraries with hotels, sightseeing and transfers bundled into one easy price.', 'service', 1, 0, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('StampIcon', 'Visa Assistance', 'End-to-end visa support for the USA, UK, Schengen, Canada, Australia and New Zealand.', 'service', 1, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Plane', 'Flight Bookings', 'Competitive fares on every major airline, included and optimised within your package.', 'service', 1, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('BedDouble', 'Hotel Arrangements', 'Hand-picked 3★ to 5★ stays, from cosy city hotels to beachfront resorts.', 'service', 1, 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('CarFront', 'Airport Transfers', 'Private, comfortable pick-ups and drop-offs so your journey is seamless from door to door.', 'service', 1, 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Camera', 'Sightseeing & Tours', 'Guided experiences and day trips that put the very best of every destination on your itinerary.', 'service', 1, 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('CreditCard', 'Installment Plans', 'Travel now, pay comfortably later with flexible, interest-friendly payment options.', 'service', 1, 6, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Ferris', 'Dubai Activities', 'Desert safaris, Burj Khalifa, dhow cruises and the full spectrum of Dubai experiences.', 'service', 1, 7, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('MoonStar', 'Umrah Packages', 'Spiritually enriching, professionally organised Umrah journeys with complete peace of mind.', 'service', 1, 8, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Globe', 'UAE-based, global reach', 'Headquartered in the UAE, we proudly serve travelers from around the world with trusted expertise.', 'why', 1, 9, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Map', 'Tailored packages', 'We craft personalized travel packages designed to suit your preferences, budget, and schedule.', 'why', 1, 10, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Wallet', 'Affordable quad-sharing', 'Save more by choosing our cost-effective quad-sharing accommodation options on group tours.', 'why', 1, 11, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('Clock', '24/7 visa support & assistance', 'Get round-the-clock visa guidance and travel support for top destinations like the USA, UK, and Schengen countries.', 'why', 1, 12, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

INSERT INTO `Setting` (`key`, `value`, `updatedAt`) VALUES
  ('company', '{"name":"RadiantWay Travel","shortName":"RadiantWay","tagline":"Effortless Journeys. Lasting Memories.","intro":"UAE-based travel experts with global reach. We craft tailored tour packages, handle your visas, and take care of every detail — so all you have to do is travel.","phone":"+971 54 786 1293","phoneHref":"tel:+971547861293","holidaysPhone":"+971 54 786 1293","visaPhone":"+971 54 786 1293","whatsapp":"https://wa.me/971547861293","email":"info@radiantwaytravel.com","emailHref":"mailto:info@radiantwaytravel.com","address":"Office No: 17, 28th Floor, Aspin Commercial Tower, Sheikh Zayed Road, Dubai, UAE","hours":"Open 24/7 — we never stop for our travellers","reviewUrl":"https://share.google/6Yg4AJOHDoq0k574Q","socials":[{"name":"Instagram","href":"https://www.instagram.com/radiantwaytravel?igsh=MW90NXQyaGl0bWZwdg==","icon":"Instagram"},{"name":"Facebook","href":"https://www.facebook.com/share/19qorzUXsM/","icon":"Facebook"},{"name":"WhatsApp","href":"https://wa.me/971547861293","icon":"MessageCircle"}],"rating":4.7,"reviewCount":39,"stats":[{"value":8,"suffix":"+","label":"Years of expertise"},{"value":50,"suffix":"k+","label":"Happy travellers"},{"value":40,"suffix":"+","label":"Destinations worldwide"},{"value":4.7,"suffix":"★","label":"Rated by 39+ reviews","decimals":1}]}', CURRENT_TIMESTAMP(3));

